dataset: oxford_spires
raw_data_root: /group/compact-3dmem/datasets/oxford_spires_processed
sampling:
  strategy: sequence
  stride: 12
evaluation:
  depth:
    gt_clip:
      min: 0.0
      max: 200.0
  points:
    icp_threshold: 0.5
